# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20160214_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='exits',
            field=models.ManyToManyField(blank=True, null=True, to='game.Exit'),
        ),
    ]
